[package]
name = "rust-microservice"
version = "0.1.0"
edition = "2021"
authors = ["Javier Orfo"]

[dependencies]
actix-web = "4.6.0"
serde_json = { version = "1.0.114", features = ["derive"] }
chrono = { version = "", features = ["serde"] }
